extends Node
## 物品数据库：定义所有物品的属性
## 自动加载为全局单例，通过 ItemDB 访问

# 物品类型枚举
enum ItemType {
	RESOURCE,   # 资源材料
	TOOL,       # 工具
	WEAPON,     # 武器
	FOOD,       # 食物
	MEDICINE,   # 药品
	BUILDING,   # 建筑材料
	AMMO,       # 弹药
	MISC        # 杂项
}

# 物品定义字典：id -> 属性
const ITEMS := {
	# ===== 资源材料 =====
	"wood": {
		"name": "木材",
		"desc": "基础建材，可用于建造和制作工具",
		"type": ItemType.RESOURCE,
		"max_stack": 99,
		"weight": 0.5,
		"color": Color(0.55, 0.35, 0.15),
	},
	"stone": {
		"name": "石头",
		"desc": "坚硬的石块，可用于建造和制作工具",
		"type": ItemType.RESOURCE,
		"max_stack": 99,
		"weight": 1.0,
		"color": Color(0.55, 0.55, 0.6),
	},
	"berry": {
		"name": "浆果",
		"desc": "野生浆果，可以直接食用恢复少量饥饿",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.1,
		"color": Color(0.8, 0.1, 0.1),
		"hunger_restore": 10,
	},
	"fiber": {
		"name": "纤维",
		"desc": "从植物中获取的纤维，可用于制作绳子和布料",
		"type": ItemType.RESOURCE,
		"max_stack": 99,
		"weight": 0.1,
		"color": Color(0.7, 0.7, 0.4),
	},
	"metal": {
		"name": "金属锭",
		"desc": "熔炼后的金属锭，用于制作高级工具和武器",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 2.0,
		"color": Color(0.7, 0.7, 0.75),
	},
	"cloth": {
		"name": "布料",
		"desc": "可用于制作衣服、绷带和帐篷",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.3,
		"color": Color(0.85, 0.8, 0.75),
	},
	"scrap": {
		"name": "废铁",
		"desc": "从废墟中找到的废铁，可熔炼为金属锭",
		"type": ItemType.RESOURCE,
		"max_stack": 99,
		"weight": 1.5,
		"color": Color(0.5, 0.5, 0.55),
	},

	# ===== 工具 =====
	"stone_axe": {
		"name": "石斧",
		"desc": "基础斧头，砍树效率提升",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 1.5,
		"color": Color(0.6, 0.5, 0.3),
		"durability": 50,
		"tool_type": "axe",
		"efficiency": 2.0,
	},
	"stone_pickaxe": {
		"name": "石镐",
		"desc": "基础镐子，挖矿效率提升",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 1.5,
		"color": Color(0.55, 0.55, 0.55),
		"durability": 50,
		"tool_type": "pickaxe",
		"efficiency": 2.0,
	},
	"metal_axe": {
		"name": "金属斧",
		"desc": "高级斧头，砍树效率大幅提升",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 2.0,
		"color": Color(0.75, 0.7, 0.5),
		"durability": 150,
		"tool_type": "axe",
		"efficiency": 4.0,
	},

	# ===== 武器 =====
	"wooden_club": {
		"name": "木棍",
		"desc": "简陋的近战武器",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.0,
		"color": Color(0.5, 0.35, 0.15),
		"damage": 8,
		"durability": 30,
	},
	"stone_spear": {
		"name": "石矛",
		"desc": "锋利的石矛，攻击距离较远",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.2,
		"color": Color(0.6, 0.55, 0.4),
		"damage": 15,
		"durability": 40,
	},
	"metal_sword": {
		"name": "金属剑",
		"desc": "锋利的金属剑，伤害高",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.8,
		"color": Color(0.8, 0.8, 0.85),
		"damage": 30,
		"durability": 100,
	},

	# ===== 食物 =====
	"cooked_meat": {
		"name": "熟肉",
		"desc": "烤熟的肉，恢复较多饥饿值",
		"type": ItemType.FOOD,
		"max_stack": 10,
		"weight": 0.3,
		"color": Color(0.7, 0.35, 0.2),
		"hunger_restore": 40,
		"health_restore": 5,
	},
	"cooked_berry": {
		"name": "烤浆果",
		"desc": "烤熟的浆果，比生浆果恢复更多",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.1,
		"color": Color(0.6, 0.1, 0.1),
		"hunger_restore": 20,
	},
	"water": {
		"name": "水",
		"desc": "干净的水，恢复口渴值",
		"type": ItemType.FOOD,
		"max_stack": 5,
		"weight": 1.0,
		"color": Color(0.3, 0.6, 0.9),
		"thirst_restore": 40,
	},

	# ===== 药品 =====
	"bandage": {
		"name": "绷带",
		"desc": "简单的绷带，恢复少量生命值",
		"type": ItemType.MEDICINE,
		"max_stack": 10,
		"weight": 0.1,
		"color": Color(0.9, 0.9, 0.9),
		"health_restore": 20,
	},
	"medkit": {
		"name": "医疗包",
		"desc": "专业医疗包，恢复大量生命值（医生专用）",
		"type": ItemType.MEDICINE,
		"max_stack": 3,
		"weight": 0.5,
		"color": Color(0.9, 0.2, 0.2),
		"health_restore": 60,
	},

	# ===== 建筑材料 =====
	"wall_wood": {
		"name": "木墙",
		"desc": "木制围墙，阻挡丧尸",
		"type": ItemType.BUILDING,
		"max_stack": 20,
		"weight": 5.0,
		"color": Color(0.55, 0.35, 0.15),
		"building": "wall",
		"health": 100,
	},
	"door_wood": {
		"name": "木门",
		"desc": "木制门，可开关",
		"type": ItemType.BUILDING,
		"max_stack": 5,
		"weight": 3.0,
		"color": Color(0.5, 0.3, 0.1),
		"building": "door",
		"health": 80,
	},

	# ===== P1: 农田作物 =====
	"seed_carrot": {
		"name": "胡萝卜种子",
		"desc": "可种植的胡萝卜种子（农民专用）",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.05,
		"color": Color(0.9, 0.6, 0.2),
		"crop": "carrot",
		"grow_time": 120.0,
	},
	"seed_potato": {
		"name": "土豆种子",
		"desc": "可种植的土豆种子（农民专用）",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.05,
		"color": Color(0.7, 0.6, 0.4),
		"crop": "potato",
		"grow_time": 150.0,
	},
	"seed_corn": {
		"name": "玉米种子",
		"desc": "可种植的玉米种子（农民专用）",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.05,
		"color": Color(0.9, 0.8, 0.2),
		"crop": "corn",
		"grow_time": 180.0,
	},
	"carrot": {
		"name": "胡萝卜",
		"desc": "新鲜的胡萝卜，可食用或烹饪",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.15,
		"color": Color(0.9, 0.5, 0.2),
		"hunger_restore": 15,
		"perishable": true,
		"rot_time": 300.0,
	},
	"potato": {
		"name": "土豆",
		"desc": "新鲜的土豆，可食用或烹饪",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.2,
		"color": Color(0.7, 0.6, 0.4),
		"hunger_restore": 20,
		"perishable": true,
		"rot_time": 400.0,
	},
	"corn": {
		"name": "玉米",
		"desc": "新鲜的玉米，可食用或烹饪",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.2,
		"color": Color(0.9, 0.8, 0.2),
		"hunger_restore": 25,
		"perishable": true,
		"rot_time": 350.0,
	},
	"raw_meat": {
		"name": "生肉",
		"desc": "生肉，需要烹饪后食用",
		"type": ItemType.FOOD,
		"max_stack": 10,
		"weight": 0.3,
		"color": Color(0.7, 0.2, 0.2),
		"hunger_restore": 10,
		"perishable": true,
		"rot_time": 150.0,
	},

	# ===== P1: 高级食物（厨师专用） =====
	"vegetable_soup": {
		"name": "蔬菜汤",
		"desc": "营养丰富的蔬菜汤（厨师专用）",
		"type": ItemType.FOOD,
		"max_stack": 5,
		"weight": 0.5,
		"color": Color(0.8, 0.6, 0.3),
		"hunger_restore": 50,
		"health_restore": 15,
		"thirst_restore": 20,
		"perishable": true,
		"rot_time": 200.0,
	},
	"meat_stew": {
		"name": "炖肉",
		"desc": "美味的炖肉，恢复大量饥饿和生命（厨师专用）",
		"type": ItemType.FOOD,
		"max_stack": 5,
		"weight": 0.5,
		"color": Color(0.6, 0.3, 0.2),
		"hunger_restore": 70,
		"health_restore": 25,
		"perishable": true,
		"rot_time": 250.0,
	},
	"canned_food": {
		"name": "罐头食品",
		"desc": "长期保存的罐头食品，不会腐烂",
		"type": ItemType.FOOD,
		"max_stack": 10,
		"weight": 0.4,
		"color": Color(0.6, 0.6, 0.6),
		"hunger_restore": 40,
		"perishable": false,
	},

	# ===== P1: 装备 =====
	"leather_armor": {
		"name": "皮甲",
		"desc": "基础护甲，减少10%伤害",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 2.0,
		"color": Color(0.6, 0.4, 0.2),
		"equip_slot": "armor",
		"damage_reduction": 0.1,
		"durability": 100,
	},
	"metal_armor": {
		"name": "金属护甲",
		"desc": "高级护甲，减少25%伤害",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 5.0,
		"color": Color(0.7, 0.7, 0.75),
		"equip_slot": "armor",
		"damage_reduction": 0.25,
		"durability": 200,
	},
	"backpack": {
		"name": "背包",
		"desc": "增加负重上限+20kg",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 1.0,
		"color": Color(0.5, 0.4, 0.3),
		"equip_slot": "backpack",
		"weight_bonus": 20.0,
	},
	"winter_coat": {
		"name": "冬装",
		"desc": "保暖衣物，增加保暖值+2",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 1.5,
		"color": Color(0.7, 0.6, 0.5),
		"equip_slot": "armor",
		"warmth_bonus": 2.0,
	},

	# ===== P1: 书籍 =====
	"medical_book": {
		"name": "医学书籍",
		"desc": "学习后获得1医学科技点",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.9, 0.2, 0.2),
		"book_type": "medical_book",
	},
	"farming_book": {
		"name": "农业书籍",
		"desc": "学习后获得1农业科技点",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.3, 0.7, 0.3),
		"book_type": "farming_book",
	},
	"cooking_book": {
		"name": "烹饪书籍",
		"desc": "学习后获得1烹饪科技点",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.9, 0.6, 0.2),
		"book_type": "cooking_book",
	},
	"engineering_book": {
		"name": "工程书籍",
		"desc": "学习后获得1工程科技点",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.4, 0.4, 0.8),
		"book_type": "engineering_book",
	},
	"combat_book": {
		"name": "战斗手册",
		"desc": "学习后获得1战斗科技点",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.8, 0.3, 0.3),
		"book_type": "combat_book",
	},
	"mechanic_book": {
		"name": "汽修书籍",
		"desc": "学习后获得1汽修科技点，解锁载具维修",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.3, 0.5, 0.8),
		"book_type": "mechanic_book",
	},
	"building_book": {
		"name": "建筑书籍",
		"desc": "学习后获得1建筑科技点，解锁高级建筑",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.6, 0.4, 0.2),
		"book_type": "building_book",
	},

	# ===== P1: 电力相关 =====
	"gasoline": {
		"name": "汽油",
		"desc": "发电机燃料",
		"type": ItemType.RESOURCE,
		"max_stack": 10,
		"weight": 1.0,
		"color": Color(0.8, 0.7, 0.2),
	},
	"electronic_parts": {
		"name": "电子元件",
		"desc": "用于制作电力设备",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.2,
		"color": Color(0.3, 0.8, 0.3),
	},
	"battery": {
		"name": "电池",
		"desc": "储存电能",
		"type": ItemType.RESOURCE,
		"max_stack": 10,
		"weight": 0.8,
		"color": Color(0.3, 0.5, 0.8),
	},

	# ===== P1: 热武器 =====
	"pistol": {
		"name": "手枪",
		"desc": "基础枪械，需要子弹",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.0,
		"color": Color(0.4, 0.4, 0.4),
		"damage": 25,
		"durability": 200,
		"ammo_type": "9mm",
		"fire_rate": 0.5,
	},
	"rifle": {
		"name": "步枪",
		"desc": "高级枪械，伤害高射程远",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 3.0,
		"color": Color(0.3, 0.35, 0.3),
		"damage": 50,
		"durability": 300,
		"ammo_type": "556",
		"fire_rate": 0.3,
	},
	"ammo_9mm": {
		"name": "9mm子弹",
		"desc": "手枪子弹",
		"type": ItemType.AMMO,
		"max_stack": 50,
		"weight": 0.02,
		"color": Color(0.7, 0.7, 0.5),
	},
	"ammo_556": {
		"name": "5.56mm子弹",
		"desc": "步枪子弹",
		"type": ItemType.AMMO,
		"max_stack": 50,
		"weight": 0.03,
		"color": Color(0.6, 0.6, 0.4),
	},
	# ===== 新增：基础资源 =====
	"mat_copper_scrap": {
		"name": "铜废料",
		"desc": "从废墟中找到的铜废料，可熔炼为铜锭",
		"type": ItemType.RESOURCE,
		"max_stack": 99,
		"weight": 1.2,
		"color": Color(0.8, 0.5, 0.2),
	},
	"mat_rope": {
		"name": "绳索",
		"desc": "制作工具、陷阱的必备材料",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.5,
		"color": Color(0.65, 0.55, 0.35),
	},
	"mat_nail": {
		"name": "钉子",
		"desc": "高级建造、修理必备材料",
		"type": ItemType.RESOURCE,
		"max_stack": 99,
		"weight": 0.1,
		"color": Color(0.6, 0.6, 0.65),
	},
	"mat_glass": {
		"name": "玻璃",
		"desc": "制作窗户、瓶子的材料",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.8,
		"color": Color(0.7, 0.85, 0.9),
	},
	"mat_plastic": {
		"name": "塑料",
		"desc": "制作电子零件、容器的材料",
		"type": ItemType.RESOURCE,
		"max_stack": 99,
		"weight": 0.3,
		"color": Color(0.8, 0.8, 0.85),
	},
	# ===== 新增：高级材料 =====
	"mat_steel_ingot": {
		"name": "钢锭",
		"desc": "顶级工具、武器、建筑材料",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 2.5,
		"color": Color(0.75, 0.75, 0.8),
	},
	"mat_gunpowder": {
		"name": "火药",
		"desc": "制作子弹、炸药的材料",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.5,
		"color": Color(0.3, 0.3, 0.3),
	},
	"mat_electronic": {
		"name": "电子零件",
		"desc": "电力设备、高级武器的核心零件",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.2,
		"color": Color(0.3, 0.5, 0.7),
	},
	"mat_battery": {
		"name": "电池",
		"desc": "为电器、手电筒供电",
		"type": ItemType.RESOURCE,
		"max_stack": 20,
		"weight": 0.5,
		"color": Color(0.2, 0.6, 0.3),
	},
	"mat_chemical": {
		"name": "化学品",
		"desc": "制药、火药的原料",
		"type": ItemType.RESOURCE,
		"max_stack": 30,
		"weight": 0.8,
		"color": Color(0.5, 0.3, 0.6),
	},
	"mat_fuel": {
		"name": "燃料",
		"desc": "汽油/柴油，用于发电机和载具",
		"type": ItemType.RESOURCE,
		"max_stack": 20,
		"weight": 1.0,
		"color": Color(0.6, 0.4, 0.1),
	},
	"mat_fertilizer": {
		"name": "肥料",
		"desc": "农田增产，加速作物生长",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 1.0,
		"color": Color(0.45, 0.35, 0.2),
	},
	# ===== 新增：工具 =====
	"tool_iron_pick": {
		"name": "铁镐",
		"desc": "采石效率高",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 2.0,
		"color": Color(0.65, 0.65, 0.7),
		"durability": 100,
		"tool_type": "pickaxe",
		"efficiency": 4.0,
	},
	"tool_hammer": {
		"name": "锤子",
		"desc": "修理建筑、拆解物品",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 1.5,
		"color": Color(0.6, 0.55, 0.4),
		"durability": 80,
		"tool_type": "hammer",
	},
	"tool_saw": {
		"name": "锯子",
		"desc": "木工制作，加工木材",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 1.0,
		"color": Color(0.65, 0.6, 0.5),
		"durability": 80,
		"tool_type": "saw",
	},
	"tool_wrench": {
		"name": "扳手",
		"desc": "修理载具、管道（汽修工专用）",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 1.2,
		"color": Color(0.7, 0.65, 0.55),
		"durability": 100,
		"tool_type": "wrench",
	},
	"tool_screwdriver": {
		"name": "螺丝刀",
		"desc": "电子设备修理（工程师专用）",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.6, 0.55, 0.5),
		"durability": 60,
		"tool_type": "screwdriver",
	},
	"tool_knife": {
		"name": "小刀",
		"desc": "剥皮、切割、防身",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 0.3,
		"color": Color(0.7, 0.7, 0.75),
		"durability": 50,
		"tool_type": "knife",
		"damage": 8,
	},
	"tool_fishing_rod": {
		"name": "钓鱼竿",
		"desc": "钓鱼获取食物",
		"type": ItemType.TOOL,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.55, 0.4, 0.25),
		"durability": 40,
		"tool_type": "fishing",
	},
	"tool_torch": {
		"name": "手持火把",
		"desc": "照明、驱赶动物",
		"type": ItemType.TOOL,
		"max_stack": 5,
		"weight": 0.5,
		"color": Color(0.9, 0.5, 0.1),
		"durability": 120,
		"tool_type": "torch",
		"light_radius": 100,
	},
	# ===== 新增：武器 =====
	"weapon_wooden_spear": {
		"name": "木矛",
		"desc": "基础近战武器",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.5,
		"color": Color(0.55, 0.4, 0.25),
		"durability": 30,
		"damage": 15,
		"attack_range": 60,
	},
	"weapon_stone_knife": {
		"name": "石刀",
		"desc": "短距离近战武器",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.55, 0.55, 0.6),
		"durability": 40,
		"damage": 12,
		"attack_range": 40,
	},
	"weapon_iron_sword": {
		"name": "铁剑",
		"desc": "中期近战武器",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 2.0,
		"color": Color(0.7, 0.7, 0.75),
		"durability": 80,
		"damage": 25,
		"attack_range": 55,
	},
	"weapon_steel_sword": {
		"name": "钢剑",
		"desc": "高级近战武器",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 2.5,
		"color": Color(0.8, 0.8, 0.85),
		"durability": 150,
		"damage": 40,
		"attack_range": 60,
	},
	"weapon_bow": {
		"name": "弓",
		"desc": "远程武器，射箭",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.0,
		"color": Color(0.55, 0.4, 0.25),
		"durability": 60,
		"damage": 20,
		"attack_range": 200,
		"ammo_type": "ammo_arrow",
	},
	"weapon_crossbow": {
		"name": "弩",
		"desc": "远程高伤害，装填慢",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 2.5,
		"color": Color(0.5, 0.4, 0.3),
		"durability": 80,
		"damage": 35,
		"attack_range": 250,
		"ammo_type": "ammo_arrow",
	},
	"weapon_pistol": {
		"name": "手枪",
		"desc": "远程武器，使用子弹",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.0,
		"color": Color(0.4, 0.4, 0.45),
		"durability": 200,
		"damage": 30,
		"attack_range": 180,
		"ammo_type": "ammo_bullet",
	},
	"weapon_rifle": {
		"name": "步枪",
		"desc": "高伤害，射程远",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 3.5,
		"color": Color(0.35, 0.35, 0.4),
		"durability": 300,
		"damage": 45,
		"attack_range": 300,
		"ammo_type": "ammo_bullet",
	},
	"weapon_shotgun": {
		"name": "霰弹枪",
		"desc": "近距高伤害",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 3.0,
		"color": Color(0.45, 0.4, 0.35),
		"durability": 250,
		"damage": 60,
		"attack_range": 100,
		"ammo_type": "ammo_shell",
	},
	"weapon_bat": {
		"name": "棒球棍",
		"desc": "常见近战武器",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 1.2,
		"color": Color(0.6, 0.45, 0.3),
		"durability": 50,
		"damage": 18,
		"attack_range": 50,
	},
	"weapon_pipe": {
		"name": "铁管",
		"desc": "易获得的近战武器",
		"type": ItemType.WEAPON,
		"max_stack": 1,
		"weight": 2.0,
		"color": Color(0.6, 0.6, 0.65),
		"durability": 60,
		"damage": 16,
		"attack_range": 45,
	},
	# ===== 新增：弹药 =====
	"ammo_arrow": {
		"name": "箭",
		"desc": "弓、弩使用的弹药",
		"type": ItemType.AMMO,
		"max_stack": 50,
		"weight": 0.05,
		"color": Color(0.6, 0.5, 0.35),
	},
	"ammo_bullet": {
		"name": "子弹",
		"desc": "手枪、步枪使用的弹药",
		"type": ItemType.AMMO,
		"max_stack": 50,
		"weight": 0.02,
		"color": Color(0.7, 0.7, 0.5),
	},
	"ammo_shell": {
		"name": "霰弹",
		"desc": "霰弹枪使用的弹药",
		"type": ItemType.AMMO,
		"max_stack": 30,
		"weight": 0.05,
		"color": Color(0.65, 0.55, 0.4),
	},
	# ===== 新增：食物与饮水 =====
	"food_raw_meat": {
		"name": "生肉",
		"desc": "饥饿+15，可能生病，需烹饪",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.5,
		"color": Color(0.7, 0.2, 0.2),
		"hunger_restore": 15,
		"perishable": true,
		"raw": true,
	},
	"food_cooked_meat": {
		"name": "烤肉",
		"desc": "饥饿+25，生命+5，基础烹饪",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.4,
		"color": Color(0.6, 0.3, 0.15),
		"hunger_restore": 25,
		"health_restore": 5,
		"perishable": true,
	},
	"food_soup": {
		"name": "炖汤",
		"desc": "饥饿+40，口渴+20，生命+15，厨师配方",
		"type": ItemType.FOOD,
		"max_stack": 10,
		"weight": 0.6,
		"color": Color(0.7, 0.5, 0.3),
		"hunger_restore": 40,
		"thirst_restore": 20,
		"health_restore": 15,
		"perishable": true,
	},
	"food_canned_meat": {
		"name": "罐装肉",
		"desc": "饥饿+30，生命+10，长期保存",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.5,
		"color": Color(0.5, 0.5, 0.55),
		"hunger_restore": 30,
		"health_restore": 10,
		"perishable": false,
	},
	"food_bread": {
		"name": "面包",
		"desc": "饥饿+20，需小麦",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.3,
		"color": Color(0.8, 0.65, 0.4),
		"hunger_restore": 20,
		"perishable": true,
	},
	"food_vegetable": {
		"name": "蔬菜",
		"desc": "饥饿+15，口渴+5，种植获得",
		"type": ItemType.FOOD,
		"max_stack": 30,
		"weight": 0.2,
		"color": Color(0.3, 0.6, 0.2),
		"hunger_restore": 15,
		"thirst_restore": 5,
		"perishable": true,
	},
	"food_fish": {
		"name": "鱼",
		"desc": "饥饿+20，钓鱼获得",
		"type": ItemType.FOOD,
		"max_stack": 20,
		"weight": 0.4,
		"color": Color(0.5, 0.6, 0.7),
		"hunger_restore": 20,
		"perishable": true,
	},
	"drink_water": {
		"name": "水",
		"desc": "口渴+30，需容器，可能不干净",
		"type": ItemType.FOOD,
		"max_stack": 10,
		"weight": 0.5,
		"color": Color(0.4, 0.6, 0.8),
		"thirst_restore": 30,
		"perishable": false,
	},
	"drink_purified_water": {
		"name": "净水",
		"desc": "口渴+40，安全饮用，需过滤",
		"type": ItemType.FOOD,
		"max_stack": 10,
		"weight": 0.5,
		"color": Color(0.5, 0.75, 0.9),
		"thirst_restore": 40,
		"perishable": false,
	},
	# ===== 新增：药品与医疗 =====
	"med_bandage": {
		"name": "绷带",
		"desc": "止血，恢复生命+10",
		"type": ItemType.MEDICINE,
		"max_stack": 20,
		"weight": 0.1,
		"color": Color(0.9, 0.9, 0.9),
		"health_restore": 10,
	},
	"med_antiseptic": {
		"name": "消毒水",
		"desc": "预防感染",
		"type": ItemType.MEDICINE,
		"max_stack": 10,
		"weight": 0.3,
		"color": Color(0.4, 0.7, 0.5),
		"prevents_infection": true,
	},
	"med_basic_kit": {
		"name": "简易急救包",
		"desc": "恢复生命30",
		"type": ItemType.MEDICINE,
		"max_stack": 5,
		"weight": 0.5,
		"color": Color(0.8, 0.3, 0.3),
		"health_restore": 30,
	},
	"med_advanced_kit": {
		"name": "高级急救包",
		"desc": "恢复生命60",
		"type": ItemType.MEDICINE,
		"max_stack": 3,
		"weight": 0.8,
		"color": Color(0.7, 0.2, 0.2),
		"health_restore": 60,
	},
	"med_surgical_kit": {
		"name": "手术包",
		"desc": "恢复生命100（医生专用）",
		"type": ItemType.MEDICINE,
		"max_stack": 2,
		"weight": 1.5,
		"color": Color(0.6, 0.15, 0.15),
		"health_restore": 100,
		"requires_doctor": true,
	},
	"med_antibiotic": {
		"name": "抗生素",
		"desc": "治疗感染",
		"type": ItemType.MEDICINE,
		"max_stack": 10,
		"weight": 0.1,
		"color": Color(0.5, 0.6, 0.8),
		"cures_infection": true,
	},
	"med_painkiller": {
		"name": "止痛药",
		"desc": "暂时忽略疼痛",
		"type": ItemType.MEDICINE,
		"max_stack": 15,
		"weight": 0.05,
		"color": Color(0.7, 0.6, 0.4),
		"pain_relief": true,
	},
	"med_vaccine": {
		"name": "疫苗",
		"desc": "预防病毒感染（稀有）",
		"type": ItemType.MEDICINE,
		"max_stack": 3,
		"weight": 0.2,
		"color": Color(0.3, 0.8, 0.5),
		"prevents_virus": true,
	},
	# ===== 新增：衣物与护甲 =====
	"cloth_basic": {
		"name": "布衣",
		"desc": "保暖+5°C，护甲0",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.7, 0.7, 0.65),
		"warmth": 5,
		"armor": 0,
		"slot": "body",
	},
	"cloth_leather": {
		"name": "皮夹克",
		"desc": "保暖+15°C，护甲5",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 1.5,
		"color": Color(0.5, 0.35, 0.2),
		"warmth": 15,
		"armor": 5,
		"slot": "body",
	},
	"cloth_winter": {
		"name": "棉大衣",
		"desc": "保暖+25°C，护甲3",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 2.0,
		"color": Color(0.6, 0.55, 0.5),
		"warmth": 25,
		"armor": 3,
		"slot": "body",
	},
	"cloth_raincoat": {
		"name": "雨衣",
		"desc": "保暖+5°C（防雨），护甲1",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.8,
		"color": Color(0.4, 0.5, 0.6),
		"warmth": 5,
		"armor": 1,
		"slot": "body",
		"waterproof": true,
	},
	"armor_military": {
		"name": "军用护甲",
		"desc": "保暖+10°C，护甲15",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 3.5,
		"color": Color(0.35, 0.4, 0.3),
		"warmth": 10,
		"armor": 15,
		"slot": "body",
	},
	"helmet": {
		"name": "头盔",
		"desc": "护甲10，头部防护",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 1.0,
		"color": Color(0.4, 0.4, 0.45),
		"warmth": 0,
		"armor": 10,
		"slot": "head",
	},
	# ===== 新增：书籍与学习材料 =====
	"book_med": {
		"name": "医学精通",
		"desc": "解锁医生科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.8, 0.3, 0.3),
		"book_type": "medical",
		"unlocks_class": "doctor",
	},
	"book_agri": {
		"name": "农业指南",
		"desc": "解锁农民科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.3, 0.7, 0.3),
		"book_type": "agriculture",
		"unlocks_class": "farmer",
	},
	"book_eng": {
		"name": "工程制图",
		"desc": "解锁工匠科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.6, 0.5, 0.3),
		"book_type": "engineering",
		"unlocks_class": "engineer",
	},
	"book_mech": {
		"name": "汽车维修",
		"desc": "解锁汽修科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.5, 0.5, 0.55),
		"book_type": "mechanic",
		"unlocks_class": "mechanic",
	},
	"book_cook": {
		"name": "高级菜谱",
		"desc": "解锁厨师科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.7, 0.5, 0.2),
		"book_type": "cooking",
		"unlocks_class": "chef",
	},
	"book_elec": {
		"name": "电工手册",
		"desc": "解锁工程师科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.4, 0.5, 0.7),
		"book_type": "electrician",
		"unlocks_class": "electrician",
	},
	"book_weapon": {
		"name": "武器改造",
		"desc": "解锁战士科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.5, 0.3, 0.3),
		"book_type": "weapon",
		"unlocks_class": "warrior",
	},
	"book_lumber": {
		"name": "重型伐木",
		"desc": "解锁伐木科技树",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.45, 0.35, 0.2),
		"book_type": "lumber",
		"unlocks_class": "lumberjack",
	},
	"book_survival": {
		"name": "生存手册",
		"desc": "提升采集/觅食效率",
		"type": ItemType.MISC,
		"max_stack": 1,
		"weight": 0.5,
		"color": Color(0.4, 0.5, 0.4),
		"book_type": "survival",
		"bonus": "gathering",
	},
	# ===== 新增：种子与农业 =====
	"seed_berry": {
		"name": "浆果种子",
		"desc": "适宜季节：春、夏，产出：浆果",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.05,
		"color": Color(0.7, 0.2, 0.2),
		"seed_type": "berry",
		"seasons": ["spring", "summer"],
		"yield": "berry",
	},
	"seed_wheat": {
		"name": "小麦种子",
		"desc": "适宜季节：春、秋，产出：小麦",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.05,
		"color": Color(0.85, 0.75, 0.4),
		"seed_type": "wheat",
		"seasons": ["spring", "autumn"],
		"yield": "food_wheat",
	},
	"seed_cabbage": {
		"name": "白菜种子",
		"desc": "适宜季节：春、秋，产出：白菜",
		"type": ItemType.RESOURCE,
		"max_stack": 50,
		"weight": 0.05,
		"color": Color(0.5, 0.7, 0.4),
		"seed_type": "cabbage",
		"seasons": ["spring", "autumn"],
		"yield": "food_vegetable",
	},
	# ===== 新增：载具配件（P2） =====
	"part_tire": {
		"name": "轮胎",
		"desc": "维修载具",
		"type": ItemType.RESOURCE,
		"max_stack": 10,
		"weight": 5.0,
		"color": Color(0.2, 0.2, 0.2),
		"part_type": "tire",
	},
	"part_engine": {
		"name": "发动机",
		"desc": "更换/升级载具",
		"type": ItemType.RESOURCE,
		"max_stack": 3,
		"weight": 20.0,
		"color": Color(0.4, 0.4, 0.45),
		"part_type": "engine",
	},
	"part_door": {
		"name": "车门",
		"desc": "维修载具",
		"type": ItemType.RESOURCE,
		"max_stack": 5,
		"weight": 8.0,
		"color": Color(0.5, 0.5, 0.55),
		"part_type": "door",
	},
	"part_armor": {
		"name": "装甲板",
		"desc": "改装防护",
		"type": ItemType.RESOURCE,
		"max_stack": 10,
		"weight": 10.0,
		"color": Color(0.45, 0.45, 0.5),
		"part_type": "armor",
	},
	"part_snowplow": {
		"name": "推雪铲",
		"desc": "冬季除雪改装",
		"type": ItemType.RESOURCE,
		"max_stack": 3,
		"weight": 15.0,
		"color": Color(0.6, 0.6, 0.65),
		"part_type": "snowplow",
	},
	# ===== 新增：其他消耗品 =====
	"item_map": {
		"name": "地图碎片",
		"desc": "解锁区域地图",
		"type": ItemType.MISC,
		"max_stack": 10,
		"weight": 0.1,
		"color": Color(0.7, 0.6, 0.4),
		"unlocks_map": true,
	},
	"item_key": {
		"name": "钥匙",
		"desc": "打开特定门/箱子",
		"type": ItemType.MISC,
		"max_stack": 10,
		"weight": 0.1,
		"color": Color(0.8, 0.7, 0.3),
		"unlocks_door": true,
	},
	"item_cigarette": {
		"name": "香烟",
		"desc": "缓解压力（但有害健康）",
		"type": ItemType.MISC,
		"max_stack": 20,
		"weight": 0.05,
		"color": Color(0.8, 0.7, 0.5),
		"stress_relief": 5,
	},
	"item_coffee": {
		"name": "咖啡",
		"desc": "提神，减少疲劳",
		"type": ItemType.MISC,
		"max_stack": 10,
		"weight": 0.2,
		"color": Color(0.4, 0.25, 0.15),
		"stamina_restore": 20,
	},
	"item_soap": {
		"name": "肥皂",
		"desc": "清洁，预防疾病",
		"type": ItemType.MISC,
		"max_stack": 10,
		"weight": 0.2,
		"color": Color(0.85, 0.85, 0.8),
		"hygiene": true,
	},
}


# 获取物品信息
func get_item(item_id: String) -> Dictionary:
	if ITEMS.has(item_id):
		return ITEMS[item_id]
	return {}


func get_item_name(item_id: String) -> String:
	if ITEMS.has(item_id):
		return ITEMS[item_id].name
	return "未知物品"


func get_item_type(item_id: String) -> int:
	if ITEMS.has(item_id):
		return ITEMS[item_id].type
	return -1


func get_max_stack(item_id: String) -> int:
	if ITEMS.has(item_id):
		return ITEMS[item_id].max_stack
	return 1


func get_weight(item_id: String) -> float:
	if ITEMS.has(item_id):
		return ITEMS[item_id].weight
	return 0.0


func get_color(item_id: String) -> Color:
	if ITEMS.has(item_id):
		return ITEMS[item_id].color
	return Color.WHITE


func item_exists(item_id: String) -> bool:
	return ITEMS.has(item_id)


func is_food(item_id: String) -> bool:
	if ITEMS.has(item_id):
		return ITEMS[item_id].type == ItemType.FOOD
	return false


func get_all_items() -> Dictionary:
	return ITEMS
